[package]
name = "task_runner"
version = "0.1.1"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/qiskit-community/spank-plugins"
description = "A command-line executable to run QRMI tasks"
readme = "README.md"
categories = ["command-line-utilities"]

[dependencies]
qrmi = { path = "../.." }
tokio = { version = "1.40.0", features = ["full"] }
env_logger = "0.11.5"
signal-hook-tokio = { version = "0.3.1", features = ["futures-v0_3"] }
signal-hook = "0.3.17"
futures = "0.3.31"
clap = { version = "4.5.29", features = ["derive"] }
eyre = "0.6.8"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
